# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: M2U1ZGQ4OTVjZjdkNTgzNGM4MWNlZmFlYTRjOWM0ODYyZDdlNGI5ZDYzOGQzN2E4NGVkZTg5NmJmZmQ4YTNkMmVmZjc4YmQzMTc4MjU3MDI3YmQyZTI0NmIwMjcxOGI4MjAwNTBiNTY0MDZiNTY1MzkwZWVkODJlZjgxYjM1ZGE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
